### ISSUE TITLE
Bug ? Conflict With ActiveAndroid?

### ISSUE THREAD

**Issue by huaxiaogood** [vinc3m1/RoundedImageView#105]
Hi:

I found a problem.My database is used with ActiveAndroid.(My device is 5.0)

When I change the ActiveAndroid(Mostly,init the ActiveAndroid),Android Studio show lots of error:

05-21 11:44:24.216  15446-15488/com.appublisher.quizbank E/﹕ mali: REVISION=Linux-r3p2-01rel3 BUILD_DATE=Tue Jul 22 19:59:34 KST 2014
05-21 11:45:45.841  15446-15446/com.appublisher.quizbank E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.appublisher.quizbank, PID: 15446
    java.lang.NoClassDefFoundError: com.makeramen.roundedimageview.RoundedTransformationBuilder$1
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:308)
            at com.activeandroid.ModelInfo.scanForModelClasses(ModelInfo.java:187)
            at com.activeandroid.ModelInfo.scanForModel(ModelInfo.java:152)
            at com.activeandroid.ModelInfo.<init>(ModelInfo.java:63)
            at com.activeandroid.Cache.initialize(Cache.java:66)
            at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:44)
            at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:34)
            at com.appublisher.quizbank.model.login.model.LoginModel.setDatabase(LoginModel.java:245)
            at com.appublisher.quizbank.model.login.activity.LoginActivity.requestCompleted(LoginActivity.java:308)
            at com.appublisher.quizbank.network.BaseRequest$8.onResponse(BaseRequest.java:218)
            at com.appublisher.quizbank.network.BaseRequest$8.onResponse(BaseRequest.java:214)
            at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
            at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5262)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)

By the way,init the db is before init roundedimageview,why roundedimageview error cause ActiveAndroid's error?

Thanks

**Comment by huaxiaogood** [comment]
I found the solution:

in Android 5.0,i must add the "com.squareup.picasso" dependencies,then it runs OK!
