### ISSUE TITLE
Support Android Studio Preview

### ISSUE THREAD

**Issue by black-snow** [vinc3m1/RoundedImageView#148]
Currently there's no preview in AS preview window for `RoundedImageView`:

> Rendering Problems The following classes could not be instantiated:
- com.makeramen.roundedimageview.RoundedImageView (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE 

> java.lang.NoClassDefFoundError: com/makeramen/roundedimageview/R$styleable
	at com.makeramen.roundedimageview.RoundedImageView.<init>(RoundedImageView.java:89)
	at com.makeramen.roundedimageview.RoundedImageView.<init>(RoundedImageView.java:83)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:465)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:172)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:105)
	...

**Comment by drakmail** [comment]
Maybe this help you: https://github.com/vinc3m1/RoundedImageView/issues/145

**Comment by black-snow** [comment]
Works now.
