### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by EbrahimSadeghi** [vinc3m1/RoundedImageView#183]
drawableToBitmap in RoundedDrawable class produce OutOfMemoryError

**Comment by vinc3m1** [comment]
Seems totally possible with a big image. Please provide more information.

**Comment by Destiny01** [comment]
java.lang.OutOfMemoryError: Failed to allocate a 1800012 byte allocation with 532600 free bytes and 520KB until OOM
                                                                                   at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                                   at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                                   at android.graphics.Bitmap.createBitmap(Bitmap.java:843)
                                                                                   at android.graphics.Bitmap.createBitmap(Bitmap.java:820)
                                                                                   at android.graphics.Bitmap.createBitmap(Bitmap.java:787)
                                                                                   at com.makeramen.roundedimageview.RoundedDrawable.drawableToBitmap(RoundedDrawable.java:134)
                                                                                   at com.makeramen.roundedimageview.RoundedDrawable.fromDrawable(RoundedDrawable.java:117)
                                                                                   at com.makeramen.roundedimageview.RoundedDrawable.fromDrawable(RoundedDrawable.java:111)
                                                                                   at com.makeramen.roundedimageview.RoundedImageView.setImageDrawable(RoundedImageView.java:233)
                                                                                   at com.bumptech.glide.request.target.ImageViewTarget.setDrawable(ImageViewTarget.java:37)
                                                                                   at com.bumptech.glide.request.animation.DrawableCrossFadeViewAnimation.animate(DrawableCrossFadeViewAnimation.java:49)
                                                                                   at com.bumptech.glide.request.animation.DrawableCrossFadeViewAnimation.animate(DrawableCrossFadeViewAnimation.java:14)
                                                                                   at com.bumptech.glide.request.target.ImageViewTarget.onResourceReady(ImageViewTarget.java:75)
                                                                                   at com.bumptech.glide.request.target.GlideDrawableImageViewTarget.onResourceReady(GlideDrawableImageViewTarget.java:66)
                                                                                   at com.bumptech.glide.request.target.GlideDrawableImageViewTarget.onResourceReady(GlideDrawableImageViewTarget.java:12)
                                                                                   at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:525)
                                                                                   at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:507)
                                                                                   at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:158)
                                                                                   at com.bumptech.glide.load.engine.EngineJob.access$100(EngineJob.java:22)
                                                                                   at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:202)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
